version: '3.6'
services:
  mysql_2:
    image: mysql:8
    container_name: mysql_2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DB_NAME
      MYSQL_USER: $MYSQL_DB_USER
      MYSQL_PASSWORD: $MYSQL_DB_PASSWORD
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    networks:
      - prestashop_2

  prestashop_2:
    image: prestashop/prestashop:8.0
    container_name: prestashop_2
    environment:
      DB_SERVER: 'mysql_2'
      DB_NAME: $MYSQL_DB_NAME
      DB_USER: $MYSQL_DB_USER
      DB_PASSWD: $MYSQL_DB_PASSWORD
      PS_DEV_MODE: 0
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: 'localhost:80'
      PS_FOLDER_ADMIN: 'admin'
      ADMIN_MAIL: 'demo@prestashop.com'
      ADMIN_PASSWORD: 'admin'
    links:
      - mysql_2
    depends_on:
      - mysql_2
    ports:
      - 8082:80
    networks:
      - prestashop_2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082" ]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  prestashop_2:
