pipeline {
    agent any
    stages {
       stage('Lancement de prestashop et de sa base de données associée') {
            steps {
                sh 'docker-compose up -d'
            }
        }
        
        stage('Création de l\'environnement virtuel') {
            steps { 
                sh 'python3 -m venv prestashop'
            }
        }
        
        stage('Activation de l\'environnement virtuel') {
            steps { 
                sh '. prestashop/bin/activate'
            }
        }
        
        stage('Installation de selenium et webdriver-manager Python modules dans l\'environnement virtuel') {
            steps { 
                sh 'pip install selenium webdriver-manager'
            }
        }
        
        stage('Attente d\'initialisation du site prestashop') {
            steps { 
                sh 'sleep 30'
            }
        }
        
        stage('Tester le titre de la page') {
            steps { 
                sh 'python3 selenium/test_prestashop_install_title.py'
            }
        }
        
        stage('Tester le menu') {
            steps { 
                sh 'python3 selenium/test_prestashop_install_menu.py'
            }
        }
        
        stage('Arrêt de prestashop et de sa base de données associée') {
            steps {
                echo 'Arrêt de prestashop et de sa base de données associée' 
                sh 'docker-compose stop'
            }
        }
        
    }
}
